version: 2.1
workflows:
  version: 2
  compile_and_push:
    jobs:
    - npmbuild_and_persist
    - pantheon/push:
        requires:
          - npmbuild_and_persist
        checkout: false
        pre-steps:
          - checkout
          - run: wp-content/themes/may2019/.gitignore
          - attach_workspace:
              at: .

orbs:
  pantheon: pantheon-systems/pantheon@0.0.1
jobs:
  npmbuild_and_persist:
    docker:
    - image: node:10.15.3
    steps:
    - checkout
    - run: cd wp-content/themes/may2019 && npm ci
    - run: cd wp-content/themes/may2019 && npm run build
    - persist_to_workspace:
        root: .
        paths:
        - wp-content/themes/may2019/dist
